version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - TZ=UTC
    command: uvicorn main:app --host 0.0.0.0 --reload

volumes:
  app:
  