version: '3.8'

services:
  web:
    build: .
    ports:
      - "8020:8020"
    volumes:
      - .:/app
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - TZ=UTC
    command: uvicorn main:app --host 0.0.0.0 --port 8020 --reload

volumes:
  app:
  
